"""add signal_entry_price to trades

Revision ID: 237ddefb7894
Revises: b14b39fe1d9b
Create Date: 2026-02-05 08:52:23.125482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237ddefb7894'
down_revision: Union[str, Sequence[str], None] = 'b14b39fe1d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('signal_entry_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_trades_strategy'), 'trades', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy'), table_name='trades')
    op.drop_column('trades', 'signal_entry_price')
    # ### end Alembic commands ###
